# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'widget.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGraphicsView, QLabel,
    QProgressBar, QPushButton, QRadioButton, QSizePolicy,
    QSlider, QSpinBox, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(1200, 800)
        self.loadButton = QPushButton(Widget)
        self.loadButton.setObjectName(u"loadButton")
        self.loadButton.setGeometry(QRect(950, 30, 101, 31))
        self.saveButton = QPushButton(Widget)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(1080, 30, 101, 31))
        self.graphicsView = QGraphicsView(Widget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(0, 0, 930, 800))
        self.outputModeBox = QComboBox(Widget)
        self.outputModeBox.setObjectName(u"outputModeBox")
        self.outputModeBox.setGeometry(QRect(1060, 130, 121, 25))
        self.outputLabel = QLabel(Widget)
        self.outputLabel.setObjectName(u"outputLabel")
        self.outputLabel.setGeometry(QRect(950, 130, 81, 19))
        self.label_2 = QLabel(Widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(950, 170, 81, 19))
        self.label_3 = QLabel(Widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(950, 210, 101, 19))
        self.blursizeSlider = QSlider(Widget)
        self.blursizeSlider.setObjectName(u"blursizeSlider")
        self.blursizeSlider.setGeometry(QRect(1090, 170, 91, 22))
        self.blursizeSlider.setMinimum(3)
        self.blursizeSlider.setMaximum(7)
        self.blursizeSlider.setSingleStep(2)
        self.blursizeSlider.setPageStep(0)
        self.blursizeSlider.setOrientation(Qt.Orientation.Horizontal)
        self.label_4 = QLabel(Widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(950, 250, 71, 19))
        self.label_5 = QLabel(Widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(950, 290, 111, 19))
        self.label_7 = QLabel(Widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(950, 390, 69, 19))
        self.colorizeModeBox = QComboBox(Widget)
        self.colorizeModeBox.setObjectName(u"colorizeModeBox")
        self.colorizeModeBox.setGeometry(QRect(1060, 390, 121, 25))
        self.label_8 = QLabel(Widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(950, 330, 111, 19))
        self.applyButton = QPushButton(Widget)
        self.applyButton.setObjectName(u"applyButton")
        self.applyButton.setGeometry(QRect(1080, 610, 101, 28))
        self.epsilonSpinBox = QSpinBox(Widget)
        self.epsilonSpinBox.setObjectName(u"epsilonSpinBox")
        self.epsilonSpinBox.setGeometry(QRect(1060, 210, 121, 25))
        self.epsilonSpinBox.setMinimum(1)
        self.epsilonSpinBox.setMaximum(5)
        self.itrateSpinBox = QSpinBox(Widget)
        self.itrateSpinBox.setObjectName(u"itrateSpinBox")
        self.itrateSpinBox.setGeometry(QRect(1060, 250, 121, 25))
        self.itrateSpinBox.setMinimum(1)
        self.saliencyThereSpinBox = QSpinBox(Widget)
        self.saliencyThereSpinBox.setObjectName(u"saliencyThereSpinBox")
        self.saliencyThereSpinBox.setGeometry(QRect(1060, 290, 121, 25))
        self.saliencyThereSpinBox.setMinimum(8)
        self.saliencyThereSpinBox.setMaximum(64)
        self.progressBar = QProgressBar(Widget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(970, 760, 211, 23))
        self.progressBar.setValue(0)
        self.resetButton = QPushButton(Widget)
        self.resetButton.setObjectName(u"resetButton")
        self.resetButton.setGeometry(QRect(950, 610, 111, 28))
        self.sampleNumSlider = QSlider(Widget)
        self.sampleNumSlider.setObjectName(u"sampleNumSlider")
        self.sampleNumSlider.setGeometry(QRect(1060, 330, 121, 22))
        self.sampleNumSlider.setMinimum(-1000)
        self.sampleNumSlider.setMaximum(1000)
        self.sampleNumSlider.setSingleStep(20)
        self.sampleNumSlider.setPageStep(20)
        self.sampleNumSlider.setOrientation(Qt.Orientation.Horizontal)
        self.saveModelButton = QPushButton(Widget)
        self.saveModelButton.setObjectName(u"saveModelButton")
        self.saveModelButton.setGeometry(QRect(1080, 80, 101, 31))
        self.label = QLabel(Widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(950, 430, 69, 19))
        self.depSpinBox = QSpinBox(Widget)
        self.depSpinBox.setObjectName(u"depSpinBox")
        self.depSpinBox.setGeometry(QRect(1060, 430, 121, 25))
        self.depSpinBox.setValue(20)
        self.blurValueLabel = QLabel(Widget)
        self.blurValueLabel.setObjectName(u"blurValueLabel")
        self.blurValueLabel.setGeometry(QRect(1060, 170, 21, 20))
        self.sampleValueLabel = QLabel(Widget)
        self.sampleValueLabel.setObjectName(u"sampleValueLabel")
        self.sampleValueLabel.setGeometry(QRect(1090, 360, 61, 20))
        self.recToolButton = QRadioButton(Widget)
        self.recToolButton.setObjectName(u"recToolButton")
        self.recToolButton.setGeometry(QRect(960, 560, 118, 23))
        self.lassoToolButton = QRadioButton(Widget)
        self.lassoToolButton.setObjectName(u"lassoToolButton")
        self.lassoToolButton.setGeometry(QRect(960, 520, 118, 23))
        self.dragToolButton = QRadioButton(Widget)
        self.dragToolButton.setObjectName(u"dragToolButton")
        self.dragToolButton.setGeometry(QRect(960, 480, 118, 23))

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.loadButton.setText(QCoreApplication.translate("Widget", u"\u5bfc\u5165\u56fe\u50cf", None))
        self.saveButton.setText(QCoreApplication.translate("Widget", u"\u5bfc\u51fa\u56fe\u50cf", None))
        self.outputLabel.setText(QCoreApplication.translate("Widget", u"\u8f93\u51fa\u6a21\u5f0f", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"\u9ad8\u65af\u6838\u5c3a\u5bf8", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"\u8fb9\u7f18\u7b80\u5316\u9608\u503c", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"\u8fed\u4ee3\u6b21\u6570", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"\u663e\u8457\u6027\u9608\u503c", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"\u7740\u8272\u98ce\u683c", None))
        self.label_8.setText(QCoreApplication.translate("Widget", u"\u91c7\u6837\u70b9\u589e\u91cf", None))
        self.applyButton.setText(QCoreApplication.translate("Widget", u"\u5e94\u7528", None))
        self.resetButton.setText(QCoreApplication.translate("Widget", u"\u91cd\u8bbe\u4e3a\u9ed8\u8ba4\u503c", None))
        self.saveModelButton.setText(QCoreApplication.translate("Widget", u"\u5bfc\u51fa\u6a21\u578b", None))
        self.label.setText(QCoreApplication.translate("Widget", u"\u6df1\u5ea6\u4e0a\u9650", None))
        self.blurValueLabel.setText("")
        self.sampleValueLabel.setText("")
        self.recToolButton.setText(QCoreApplication.translate("Widget", u"\u77e9\u5f62\u9009\u6846", None))
        self.lassoToolButton.setText(QCoreApplication.translate("Widget", u"\u5957\u7d22", None))
        self.dragToolButton.setText(QCoreApplication.translate("Widget", u"\u62d6\u62fd\u79fb\u52a8", None))
    # retranslateUi

